// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7QmnEK36qat8Sam-Rpbu_mfOfAt1JtqQ',
    appId: '1:991435007163:android:605a65d8394e5e71d9b59e',
    messagingSenderId: '991435007163',
    projectId: 'click-express-de9b3',
    storageBucket: 'click-express-de9b3.firebasestorage.app',
    databaseURL: 'https://click-express-de9b3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlMgNZNigdcDjco9Y4D2gZd0gh6-6Iy0',
    appId: '1:991435007163:ios:7ddb6b9f20ee7a83d9b59e',
    messagingSenderId: '991435007163',
    projectId: 'click-express-de9b3',
    storageBucket: 'click-express-de9b3.firebasestorage.app',
    iosBundleId: 'com.example.clickexpress',
    databaseURL: 'https://click-express-de9b3-default-rtdb.firebaseio.com',
  );
}
